name: Check Mod Version

on:
  pull_request:
    branches:
      - main
    paths:
      - src/main/java/com/yuseix/dragonminez/**
    types: [ opened, synchronize ]

permissions:
  contents: read # for actions/checkout to fetch code
  pull-requests: write # for actions/github-script to comment on the pull request


jobs:
  check-version:
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current mod_version from main branch
        run: |
          # Fetch the main branch without merging it
          git fetch origin main:main
          # Extract the mod_version from gradle.properties on the main branch
          main_version=$(git show main:gradle.properties | grep -E '^mod_version=' | cut -d'=' -f2)
          echo "Main branch mod_version: $main_version"
          echo "::set-output name=main_version::$main_version"
        id: get_main_version

      - name: Get mod_version from PR branch
        run: |
          # Extract the mod_version from gradle.properties on the PR branch
          pr_version=$(grep -E '^mod_version=' gradle.properties | cut -d'=' -f2)
          echo "PR branch mod_version: $pr_version"
          echo "::set-output name=pr_version::$pr_version"
        id: get_pr_version

      - name: Compare versions
        run: |
          if [ "${{ steps.get_main_version.outputs.main_version }}" == "${{ steps.get_pr_version.outputs.pr_version }}" ]; then
            echo "Error: mod_version has not been updated!"
            exit 1
          fi
        id: compare_versions

      - name: Comment on PR if version is unchanged
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: `⚠️ The \`mod_version\` in \`gradle.properties\` has not been updated. Please label the PR to automatically change the version.\n\n
              ⚠️ El \`mod_version\` en \`gradle.properties\` no se ha actualizado. Por favor, dale un label al PR para cambiar la versión automáticamente.`
            });
